language: node_js
node_js:
  - "0.12"
sudo: false
before_install: 
  - npm install -g grunt-cli
  - pip install --user codecov
install: npm install
before_script: grunt build
after_success:
  - codecov
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
